export const ACCESSORIES = [
  { id: "wearing a fedora", value: "중절모" },
  { id: "reading the Bible", value: "성서" },
  { id: "grabbing a golden spoon", value: "금수저" },
  { id: "eating an ice cream cone", value: "아이스크림 콘" },
  { id: "holding a christmas gift box", value: "크리스마스 선물" },
  { id: "typing on a laptop", value: "랩탑 컴퓨터" },
  { id: "holding a buddhist beads", value: "염주" },
  { id: "putting on a gold chain", value: "금목걸이" },
  { id: "wearing a disposable mask", value: "일회용 마스크" },
  { id: "with a soccer ball", value: "축구공" },
  { id: "holding a torch", value: "횃불" },
  { id: "reading the Quran", value: "쿠란" },
  { id: "eating a pepperoni pizza", value: "페퍼로니 피자" },
  { id: "putting on a crown", value: "왕관" },
  { id: "holding a cotton candy", value: "솜사탕" },
  { id: "with a turntable", value: "턴테이블" },
  { id: "on a skateboard", value: "스케이트보드" },
  { id: "holding a bouquet", value: "꽃다발" },
  { id: "riding a harley davidson", value: "할리 데이비슨" },
  { id: "wearing sunglasses", value: "썬글라스" },
  { id: "holding a polearm", value: "폴암" },
  { id: "holding a microphone", value: "마이크" },
  { id: "with a teddy bear", value: "곰인형" },
  { id: "holding a tumbler", value: "텀블러" },
  { id: "grabbing colorful balloons", value: "풍선" },
  { id: "holding the BTS Army Bomb", value: "아미밤" },
  { id: "holding an ancient bronze ware", value: "청동기" },
  { id: "drinking a draft beer", value: "역전 할머니 맥주" },
  { id: "with crypto currencies", value: "암호화폐" },
  { id: "eating a tanghulu", value: "탕후루" },
];
