export const BREEDS = [
  { id: "poodle", value: "푸들" },
  { id: "pomeranian", value: "포메라니안" },
  { id: "pug", value: "퍼그" },
  { id: "maltese dog", value: "말티즈" },
  { id: "seberian husky", value: "시베리안 허스키" },
  { id: "welsh corgi", value: "웰시 코기" },
  { id: "bulldog", value: "불독" },
  { id: "golden retriever", value: "골든 리트리버" },
  { id: "dachshund", value: "닥스훈트" },
  { id: "chihuahua", value: "치와와" },
  { id: "german shepherd", value: "저먼 셰펴드" },
  { id: "korean jindo", value: "진돗개" },
  { id: "bichon frise", value: "비숑 프리제" },
  { id: "shiba inu", value: "시바견" },
  { id: "chow chow", value: "차우 차우" },
  { id: "yorkshire terrier", value: "요크셔테리어" },
  { id: "shih tzu", value: "시츄" },
  { id: "samoyed", value: "사모예드" },
  { id: "dalmatian", value: "달마시안" },
  { id: "afghan hound", value: "아프간 하운드" },
  { id: "border collie", value: "보더 콜리" },
  { id: "old english sheepdog", value: "올드 잉글리쉬 쉽독" },
  { id: "boston terrier", value: "보스턴 테리어" },
  { id: "cocker spaniel", value: "코카 스파니엘" },
  { id: "papillon dog", value: "파피용" },
  { id: "mixed-breed dog", value: "믹스견" },
];
