export const LOCATIONS = [
  { id: "in space", value: "우주" },
  { id: "in Gobi Desert", value: "고비 사막" },
  { id: "on a cloud", value: "구름 위" },
  { id: "in New York Times Square", value: "뉴욕 타임스퀘어" },
  { id: "in the north pole", value: "북극" },
  { id: "in a subway station", value: "지하철역" },
  { id: "in Machu Picchu", value: "마추 픽추" },
  { id: "in Fiji island", value: "피지 섬" },
  { id: "in a night club", value: "나이트 클럽" },
  { id: "in Gyeongbokgung Palace", value: "경복궁" },
  { id: "in a cave", value: "동굴" },
  { id: "in front of a Pyramid", value: "피라미드" },
  { id: "on a mountain summit", value: "산꼭대기" },
  { id: "with green chroma key background", value: "크로마키" },
  { id: "on a yacht", value: "요트" },
  { id: "in china town", value: "차이나 타운" },
  { id: "at hot springs", value: "온천" },
  { id: "in a future city", value: "미래도시" },
  { id: "in a ski resort", value: "스키장" },
  { id: "in Santorini island", value: "산토리니 섬" },
  { id: "in a fitness center", value: "헬스장" },
];
